config/routes.rb
Rails.application.routes.draw do

  root "home#index"

  namespace :api, defaults: { format: 'json' } do
    namespace :v1 do
      resources :comments, only: [:create, :index, :show, :update, :destroy]
    end
  end

  get '/users/verify', to: 'verification#new', as: 'verify'
  post '/users/verify', to: 'verification#create'
  post '/users/resend'
  post '/notification', to: 'notification#create'
  put '/notification', to: 'notification#update'
  delete '/notification', to: 'notification#destroy'
  get '/api_request', to: 'external_application#index'

  namespace :admin do
    get '/dashboard', to: 'dashboard#index'
    resources :users, only:[:index, :update]
  end


  resources :documents, only:[:index] #TODO move this?

  resources :users, only:[:new, :create, :edit, :update, :show] do
    resources :documents, only:[:new, :create, :show]
    scope module: 'users' do
      resources :folders, only:[:new, :create, :index, :edit, :update]
    end
    resources :comments, only: [:new, :create, :destroy, :edit, :update]
  end

  resources :folders, only:[:index, :show, :update]
  resources :downloads, only:[:create]

  get '/dashboard', to: 'dashboard#index'
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete '/logout', to: 'sessions#destroy'
  get '/:user_name', to: 'users#show'

end

app/controllers/admin/dashboard_controller.rb
class Admin::DashboardController < Admin::AdminController
  def index

  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index

  end
end

app/views/dashboard/index.html.erb
<div class="container dashboard">

  <div class="row">
    <div class="col-md-6 title-dashboard">
      <h2><%= link_to "Create a Folder", new_user_folder_path(current_user) %></h2>
    </div>
    <div class="col-md-6 title-dashboard">
      <h2><%= link_to "Upload a file", new_user_document_path(current_user) %></h2>
    </div>
  </div>

  <div class="row">

    <div class="col-md-6 icon-dashboard">
      <a href='/users/<%= current_user.id %>/folders/new'><image src='assets/new_folder_image.svg'></image></a>
    </div>

    <div class="col-md-6 icon-dashboard">
      <a href='/users/<%= current_user.id %>/documents/new'><image src='assets/upload_file_image.svg'></image></a>
    </div>

  </div>

  <div class="row">
    <div class="col-md-6 title-dashboard">
      <h2><%= link_to "View Personal Folders", user_folders_path(current_user) %></h2>
    </div>
    <div class="col-md-6 title-dashboard">
      <h2><%= link_to "View Public Folders", folders_path %></h2>
    </div>
  </div>

  <div class='row'>

    <div class="col-md-6 icon-dashboard">
      <a href="/users/<%= current_user.id %>/folders"><image src='assets/personal_files_image.svg'></image></a>
    </div>

    <div class="col-md-6 icon-dashboard">
      <a href="/folders"><image src='assets/public_files_image.svg'></image></a>
    </div>

  </div>

</div>