config/routes.rb
Rails.application.routes.draw do

  root "home#index"

  namespace :api, defaults: { format: 'json' } do
    namespace :v1 do
      resources :comments, only: [:create, :index, :show, :update, :destroy]
    end
  end

  get '/users/verify', to: 'verification#new', as: 'verify'
  post '/users/verify', to: 'verification#create'
  post '/users/resend'
  post '/notification', to: 'notification#create'
  put '/notification', to: 'notification#update'
  delete '/notification', to: 'notification#destroy'
  get '/api_request', to: 'external_application#index'

  namespace :admin do
    get '/dashboard', to: 'dashboard#index'
    resources :users, only:[:index, :update]
  end


  resources :documents, only:[:index] #TODO move this?

  resources :users, only:[:new, :create, :edit, :update, :show] do
    resources :documents, only:[:new, :create, :show]
    scope module: 'users' do
      resources :folders, only:[:new, :create, :index, :edit, :update]
    end
    resources :comments, only: [:new, :create, :destroy, :edit, :update]
  end

  resources :folders, only:[:index, :show, :update]
  resources :downloads, only:[:create]

  get '/dashboard', to: 'dashboard#index'
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete '/logout', to: 'sessions#destroy'
  get '/:user_name', to: 'users#show'

end

app/models/folder.rb
class Folder < ApplicationRecord
  belongs_to :user
  scope :unrestricted_folders, -> { where(permission_level: 'unrestricted') }

  has_many :containers, dependent: :destroy
  has_many :subfolders,
            through: :containers,
            source: :containable,
            source_type: 'Folder',
            dependent: :destroy
  has_many :documents,
            through: :containers,
            source: :containable,
            source_type: 'Document',
            dependent: :destroy

  alias_attribute :authorized_users, :users
  has_many :folder_permissions
  has_many :users, through: :folder_permissions

  alias_attribute :parent, :folder
  has_one :container, as: :containable
  has_one :folder, through: :container

  enum permission_level: %w(restricted unrestricted)

  def set_parent(parent_folder_id)
    if parent_folder_id
      parent = Folder.find(parent_folder_id)
      parent.subfolders << self
      "#{name} was added to #{parent.name}"
    else
      "#{name} was added"
    end
  end

  def accessible?(visitor)
    if user.active? && visitor
      unrestricted? || authorized_users.include?(visitor) || visitor.admin? || visitor == user
    elsif user.active?
      unrestricted?
    else
      return false
    end
  end
end

app/controllers/folders_controller.rb
class FoldersController < ApplicationController

  def index
    @folders = Folder.unrestricted_folders
  end

  def show
    @folder = Folder.find(params[:id])
    @documents = @folder.documents
    unless @folder.accessible?(current_user)
      render file: 'public/404', status: 404
    end
  end

  def update
    @user = User.find_by(email: params[:folder][:folder_permissions])
    @folder = Folder.find(params[:id])
    @folder.authorized_users << @user
    flash[:success] = "#{@user.name} has been granted access!"
    redirect_to dashboard_path
  end
end

app/controllers/users/folders_controller.rb
class Users::FoldersController < ApplicationController
  def new
    @folder = Folder.new
  end

  def create
    @folder = current_user.folders.new(folder_params)
    if @folder.save
      flash[:success] = @folder.set_parent(parent_folder[:parent])
      redirect_to dashboard_path
    else
      flash.now[:error] = @folder.errors.full_messages.join('. ')
      render :new
    end
  end

  def index
    @folders = User.find(params[:user_id]).folders.select do |folder|
      folder.accessible?(current_user)
    end
  end

  def edit
    @folder = current_user.folders.find(params[:id])
  end

  def update
    @folder = current_user.folders.find(params[:id])
    if @folder.update(folder_params)
      flash[:success] = 'Your folder has been updated'
      redirect_to folder_path(@folder)
    else
      flash.now[:error] = @folder.errors.full_messages.join('. ')
      render :edit
    end
  end

  private
    def folder_params
      params.require(:folder).permit(:name, :permission_level)
    end

    def parent_folder
      params.require(:folder).permit(:parent)
    end
end

app/views/folders/index.html.erb
<% @folders.each do |folder| %>
  <%= link_to folder.name, folder_path(folder.id) %><br>
<% end %>

app/views/folders/show.html.erb
<div class="container">
  <h1><%= @folder.name %></h1>
  <%= link_to "Edit Folder", edit_user_folder_path(current_user.id, @folder.id) %>
<div>
  <h4>Share this folder with another user.</h4>
  <%= form_for @folder do |f| %>
    <%= f.label 'Email: ' %>
    <%= f.text_field :folder_permissions, value: 'example@example.com' %>
    <%= f.submit 'Grant Access' %>
  <% end %>
</div>
<div>
  <table>
    <tr><th>Documents in this folder</th></tr>
    <%= form_for(:download, url: downloads_path) do |f| %>
      <% @documents.each do |document| %>
      <tr>
      <td><%= link_to document.filename, user_document_path(current_user.id, document.id) %></td>
        <td><%= f.check_box(document.id)%>
        <%= f.label "Download?" %></td>
      </tr>
      <% end %>
      <tr><td><%= f.submit "Download Selected Files" %></td></tr>
    <% end %>
  </table>
</div>

<% if current_user %>
  <%= link_to "Upload File", new_user_document_path(current_user.id), class: 'btn' %>
<% end %>