config/routes.rb
Rails.application.routes.draw do

  root "home#index"

  namespace :api, defaults: { format: 'json' } do
    namespace :v1 do
      resources :comments, only: [:create, :index, :show, :update, :destroy]
    end
  end

  get '/users/verify', to: 'verification#new', as: 'verify'
  post '/users/verify', to: 'verification#create'
  post '/users/resend'
  post '/notification', to: 'notification#create'
  put '/notification', to: 'notification#update'
  delete '/notification', to: 'notification#destroy'
  get '/api_request', to: 'external_application#index'

  namespace :admin do
    get '/dashboard', to: 'dashboard#index'
    resources :users, only:[:index, :update]
  end


  resources :documents, only:[:index] #TODO move this?

  resources :users, only:[:new, :create, :edit, :update, :show] do
    resources :documents, only:[:new, :create, :show]
    scope module: 'users' do
      resources :folders, only:[:new, :create, :index, :edit, :update]
    end
    resources :comments, only: [:new, :create, :destroy, :edit, :update]
  end

  resources :folders, only:[:index, :show, :update]
  resources :downloads, only:[:create]

  get '/dashboard', to: 'dashboard#index'
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete '/logout', to: 'sessions#destroy'
  get '/:user_name', to: 'users#show'

end

app/models/document.rb
class Document < ApplicationRecord
  before_destroy :remove_from_storage
  belongs_to :user
  has_many :comments, dependent: :destroy

  has_one :container, as: :containable
  has_one :folder, through: :container, dependent: :destroy
  alias_attribute :parent, :folder


  alias_attribute :parent, :folder

  has_one :container, as: :containable, dependent: :destroy
  has_one :folder, through: :container

  def set_parent(parent_folder_id)
    if parent_folder_id
      parent = Folder.find(parent_folder_id)
      parent.documents << self
      "#{filename} was added to #{parent.name}"
    else
      "#{filename} was added"
    end
  end

  def amazon_path
    "#{parent.user_id}/#{parent.id}"
  end

  def remove_from_storage
  #   bucket = ENV['S3_BUCKET']
  #   bucket.object(amazon_path+"/#{filename}").delete
  end
end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController

  def new
    @document = Document.new
    @folders = current_user.folders
  end

  def create
    file_to_upload = params[:document][:file]
    bucket = S3.bucket(S3_BUCKET.name)

    obj = bucket.object(filepath)
    obj.put(
      acl: "public-read",
      body: file_to_upload
    )
    @document = Document.new(user_id: user_params, filename: document_params[:file].original_filename, content_type: document_params[:file].content_type, url: obj.public_url)

    if @document.save
      flash[:success] = @document.set_parent(parent_folder[:parent])
      redirect_to folder_path(parent_folder[:parent])
    else
      flash.new[:notice] = 'There was an error'
      render :new
    end
  end

  def index
    # @root_folder = current_user.folders[0]
    # @folders = current_user.folders.drop(1)
  end

  def show
    @document = Document.find(params[:id])
    # @comment = @document.comments.new
  end

  private

  def document_params
    params.require(:document).permit(:id, :file)
  end

  def filepath
    params[:user_id] + "/" + params[:document][:parent] + "/" + document_params[:file].original_filename
  end

  def user_params
    params.require(:user_id)
  end

  def parent_folder
    params.require(:document).permit(:parent)
  end
end

app/views/documents/index.html.erb
<div class="container">
  <h3 class="root_folder"><%= @root_folder.name %></h3>
  <% @folders.each do |folder| %>
    <h4 class="user_folder"> <%= folder.name %></h4>
      <ul class="user_folder_files">
        <% folder.documents.each do |document| %>
          <li class="user_folder_file"> <%= document.filename %> </li>
        <% end %>
      </ul>
  <% end %>
</div>

app/views/documents/new.html.erb
<div class="row">
	<div class="container">
		<h1>Upload a file</h1>
		<%= form_for([@folders, @document], url: user_documents_path, enctype: 'multipart/form-data') do |f| %>
		  <div class="form-group">
				<label for="parent-folder">Parent Folder</label>
				<%= select_tag "document[parent]", options_from_collection_for_select(@folders, "id", "name"), prompt: false %>
		  </div>
		  <div class="form-group">
				<%= f.file_field :file, class:'custom-file' %>
			</div>
				<%= f.submit 'Upload File', class: 'btn btn-default' %>
		<% end %>
	</div>
</div>

app/views/documents/show.html.erb
<div class="container">
  <div class="well well-lg">
    <h1><%= @document.filename %></h1>
    <p><%= link_to "View Document", @document.url %></p>
    <p>File type: <%= @document.content_type %></p>
    <p><%= link_to "Delete", "#", method: :destroy %></p>
  </div>
</div>

<div class="container comments">
  <div class="row">
    <div class="col-sm-12">
      <h3>Comments</h3>
    </div>
  </div>

<% if @document.comments %>
  <% @document.comments.each do |comment| %>
    <div class="row comment">
      <div class="col-sm-1">
        <div class="thumbnail">
          <image class='profile_icon' src='/assets/user_icon.svg'></image>
        </div>
      </div>

      <div class="col-sm-11">
        <div class="panel panel-default">
          <div class="panel-heading">
            <strong> <%= comment.user.name %> </strong>
            <span class="text-muted"><%= format_comment_time(comment.created_at) %></span>
            <span class="text-muted"><%= link_to "Edit", edit_user_comment_path(comment_id: comment.id) %></span>
            <span class="text-muted"><%= link_to "Delete", user_comment_path(comment_id: comment.id), method: :delete %></span>
          </div>
          <div class="panel-body">
            <%= comment.content %>
          </div>
        </div>
      </div>
    </div>
  <% end %>
<% end %>

  <%= form_for(:comment, url: user_comments_path(current_user), class: "form-group") do |f| %>
    <%= f.text_area :content, placeholder: "Write a comment...", class: "form-control" %>
    <%= f.hidden_field :document, value: @document.id %>
    <%= f.submit "Add Comment", class: "form-control btn btn-primary" %>
  <% end %>
</div>